MEMORY
{
    rom  (rx)  : ORIGIN = 0x01000000, LENGTH = 16M

    /* WARNING!!!: Assumption is that workram will always be
       a multiple of 32 bytes. If this become not true for some interesting
       reason, we have to modify the code boot.S. */
    sram (rwx) : ORIGIN = 0x10000000, LENGTH = 192K
}

ENTRY(__start)

REGION_ALIAS("REGION_TEXT", sram);

_bootrom_text_area = _bootrom_data_area - _text_size;

INCLUDE chips/tsb/scripts/common.ld
